--- GNUmakefile.orig	2009-07-10 13:15:22.000000000 +0900
+++ GNUmakefile	2009-07-10 13:23:07.000000000 +0900
@@ -6,9 +6,9 @@
 
 #FDEBUG= 1
 
-CC?= gcc
-CFLAGS+= -DBUILD="\"$(VERSION)\""
-LDFLAGS+= -L/usr/local/lib
+CC= __CC__
+CFLAGS+= __CFLAGS__ -I__PREFIX__/include -I__PREFIX__/include/ncurses -DBUILD="\"$(VERSION)\""
+LDFLAGS+= __LDFLAGS__ -L/usr/local/lib
 LIBS+= -lncurses
 
 # This sort of sucks but gets rid of the stupid warning and should work on
@@ -27,10 +27,10 @@
 CFLAGS+= -Wundef -Wbad-function-cast -Winline -Wcast-align
 endif
 
-PREFIX?= /usr/local
+PREFIX= __PREFIX__
 INSTALLDIR= install -d
-INSTALLBIN= install -g bin -o root -m 555
-INSTALLMAN= install -g bin -o root -m 444
+INSTALLBIN= install -m 555
+INSTALLMAN= install -m 444
 
 SRCS= $(shell echo *.c|sed 's|osdep-[a-z0-9]*.c||g')
 include config.mk
@@ -53,5 +53,5 @@
 install:	all
 		$(INSTALLDIR) $(DESTDIR)$(PREFIX)/bin
 		$(INSTALLBIN) tmux $(DESTDIR)$(PREFIX)/bin/tmux
-		$(INSTALLDIR) $(DESTDIR)$(PREFIX)/man/man1
-		$(INSTALLMAN) tmux.1 $(DESTDIR)$(PREFIX)/man/man1/tmux.1
+		$(INSTALLDIR) $(DESTDIR)$(PREFIX)/share/man/man1
+		$(INSTALLMAN) tmux.1 $(DESTDIR)$(PREFIX)/share/man/man1/tmux.1
