diff -ru Makefile.original Makefile
--- Makefile.original	2009-11-12 22:00:48.000000000 +0900
+++ Makefile	2010-01-27 02:00:28.000000000 +0900
@@ -25,7 +25,7 @@
 	@$(MAKE) $(MAKEFLAGS) progs
 
 osx:
-	@$(MAKE) XCFLAGS="-arch ppc -arch i386" $(MAKEFLAGS) progs
+	@$(MAKE) XCFLAGS="-arch ppc -arch i386" XCFLAGS=-I/opt/local/include XLDFLAGS=-L/opt/local/lib $(MAKEFLAGS) progs
 
 mingw:
 	@$(MAKE) CROSS_COMPILE=mingw32- LIBS="-lws2_32 -lwinmm -lcrypto -lgdi32" THREADLIB= EXT=.exe $(MAKEFLAGS) progs
